name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Create environment file
      - name: Create backend production env file
        run: |
          cat << EOF > .env.production
          NODE_ENV=production
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN=7d
          SMTP_HOST=${{ secrets.SMTP_HOST }}
          SMTP_PORT=587
          SMTP_USER=${{ secrets.SMTP_USER }}
          SMTP_PASS=${{ secrets.SMTP_PASS }}
          EMAIL_FROM=billeasy@plewa.au
          NEXT_PUBLIC_APP_URL=http://15.235.193.214:3001
          EOF

      - name: Build Docker image
        run: |
          docker build -t billeasy:${{ github.sha }} .
          docker save billeasy:${{ github.sha }} > billeasy-image_${{ github.sha }}.tar

      # - name: List files in the repository
      #   run: |
      #     ls .

      # - name: Upload backend image artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: billeasy-image
      #     path: billeasy-image_${{ github.sha }}.tar

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #    # Download artifacts
  #     - name: Download image
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: billeasy-image
  #         path: .

      # Deploy to server
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "billeasy-image_${{ github.sha }}.tar"
          target: "/home/ubuntu/billeasy"
          rm: true

      # Load and start containers
      - name: Deploy containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/ubuntu/billeasy
            docker load < billeasy-image_${{ github.sha }}.tar
            docker stop billeasy || true
            docker rm billeasy || true
            # Run the new container
            docker run -d \
              --name billeasy \
              -p 3001:3000 \
              -e NODE_ENV=production \
              --restart unless-stopped \
              billeasy:${{ github.sha }}
 
